# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoapodsAF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoapodsAF

pod 'Alamofire', '~> 5.0'


  target 'CocoapodsAFTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoapodsAFUITests' do
    # Pods for testing
  end

end
